site_name: Учебные проекты
site_url: https://f1noll.github.io/

theme:
  name: material
  language: ru

docs_dir: docs
site_dir: ../docs

nav:
  - Главная: index.md
  - Об авторе: me.md
  - LR-2: LR-2/index.md
  - LR-3 отчет: LR3.md
  - Лабораторные работы:
      - Лабораторная 1: labs/lab1.md
      - Лабораторная 2: labs/lab2.md
      - Лабораторная 3: labs/lab3.md